name: Continuous Integration
on: pull_request

jobs: 
  continuous-integration: 
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4
      
      - name: run docker compose
        run: docker-compose up -d
        
      - name: check all containers
        run: docker-compose ps

      - name: check nodejs log
        run: docker container logs nodejs
      
      - name: run all tests      
        run: docker-compose exec -T nodejs npm run test

