name: Continuous Integration

on: pull_request

jobs: 
  continuous-integration: 
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: setup docker compose
        run: docker-compose up -d --build
        
      - name: wait for services
        run: docker-compose exec nodejs npm start
        
      - name: run integration test
        run: docker-compose exec nodejs npm run test
        
      - name: Tear down Docker containers
        run: docker-compose down
          
      

