name: Continuous Integration
on: pull_request

jobs:
  runner-job:
    runs-on: ubuntu-latest
    
    services:      
      postgres:        
        image: postgres        

        env:
          POSTGRES_PASSWORD: 1234        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:          
          - 5432:5432

      redis:
        image: redis:alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5       
        ports:
          - 6379:6379

    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create emailservice db
        run: sh -c "PGPASSWORD=1234 psql -h localhost -U postgres -f $(pwd)/create.sql"            
        
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm ci
        
      - name: build
        run: npm run build             
    

      - name: install pm2
        run: npm i pm2 -g       
          
      - name: start bull queue and node.js server on background
        run: sh -c "pm2 start ./dist/src/init-queue.js && pm2 start ./dist/src/index.js"
        env:          
          PORT: 4331
          HOST: localhost          
          DATABASE_URL: "postgresql://postgres:1234@localhost:5432/emailservice"
          MAIL_HOST: sandbox.smtp.mailtrap.io 
          MAIL_PORT: 2525
          MAIL_USERNAME: 935d0e69c95e45
          MAIL_PASSWORD: ba0f07267fab5f
          REDIS_HOST: localhost
          REDIS_PORT: 6379
      
      - name: Run all tests
        run: npm run test
        env:
          # The hostname used to communicate with the PostgreSQL service container
          PORT: 4331
          HOST: localhost          
          DATABASE_URL: "postgresql://postgres:1234@localhost:5432/emailservice"
          MAIL_HOST: sandbox.smtp.mailtrap.io 
          MAIL_PORT: 2525
          MAIL_USERNAME: 935d0e69c95e45
          MAIL_PASSWORD: ba0f07267fab5f
      
      - name: Stop node server
        run: bash -c "pm2 stop all"
      
      - name: kill pm2 proccess
        run: bash -c "pm2 kill"